from __future__ import annotations

import os
import time
from typing import Any

import requests
import streamlit as st

st.set_page_config(
    page_title="Repository Code Explainer",
    page_icon="🧠",
    layout="wide",
    initial_sidebar_state="expanded",
)

BACKEND_URL = os.getenv("BACKEND_URL", "http://127.0.0.1:8000").rstrip("/")
API_URL = f"{BACKEND_URL}/api/analyze"


def inject_css() -> None:
    st.markdown(
        """
        <style>
        .hero {padding: 18px 20px; border-radius: 18px; border: 1px solid rgba(100,100,100,.18); background: linear-gradient(135deg, rgba(99,102,241,.12), rgba(20,184,166,.09));}
        .hero h1 {margin: 0; font-size: 2.25rem;}
        .hero p {margin: 8px 0 0 0; opacity: .8;}
        .badge {display:inline-block; padding:4px 10px; margin:6px 6px 0 0; border-radius:999px; border:1px solid rgba(100,100,100,.25); font-size:.85rem;}
        .small {font-size:.86rem; opacity:.75;}
        .filecard {padding:10px 12px; border-radius:10px; border:1px solid rgba(100,100,100,.15); margin-bottom:8px;}
        </style>
        """,
        unsafe_allow_html=True,
    )


def human_size(n: int) -> str:
    value = float(n)
    for unit in ["B", "KB", "MB", "GB"]:
        if value < 1024:
            return f"{value:.1f} {unit}"
        value /= 1024
    return f"{value:.1f} TB"


def get_json(url: str, timeout: float = 10) -> dict[str, Any]:
    response = requests.get(url, timeout=timeout)
    response.raise_for_status()
    return response.json()


def start_job(repository_url: str) -> dict[str, Any]:
    response = requests.post(API_URL, json={"github_url": repository_url.strip()}, timeout=(10, 20))
    if response.status_code >= 400:
        try:
            detail = response.json().get("detail", response.text)
        except ValueError:
            detail = response.text
        raise RuntimeError(str(detail))
    return response.json()


def poll_job(job_id: str, max_wait: int = 900) -> dict[str, Any]:
    status_url = f"{BACKEND_URL}/api/jobs/{job_id}"
    progress = st.progress(0, text="Starting analysis...")
    status_box = st.empty()
    started = time.time()
    last = None
    while time.time() - started < max_wait:
        data = get_json(status_url, timeout=15)
        current = (data.get("progress"), data.get("stage"), data.get("message"))
        if current != last:
            progress.progress(int(data.get("progress", 0)), text=data.get("message", "Analyzing..."))
            status_box.caption(f"Stage: {data.get('stage', 'working')} · Elapsed: {data.get('elapsed_seconds', 0)} s")
            last = current
        if data.get("status") == "completed":
            progress.progress(100, text="Analysis complete")
            return data
        if data.get("status") == "failed":
            raise RuntimeError(data.get("error") or data.get("message") or "Analysis failed")
        time.sleep(1.2)
    raise TimeoutError("The analysis is still running after 15 minutes. Please refresh and try a smaller repository.")


def render_report(data: dict[str, Any]) -> None:
    report = data["report"]
    st.success("Repository explanation generated by the local LLM.")
    metrics = [
        ("Files", report["total_files"]),
        ("Source", report["source_files"]),
        ("Notebooks", report["notebook_files"]),
        ("Docs", report["documentation_files"]),
        ("Config", report["configuration_files"]),
        ("Data / Schema", report["data_schema_files"]),
        ("Tests", report["test_files"]),
        ("Assets", report["asset_files"]),
    ]
    cols = st.columns(4)
    for i, (label, value) in enumerate(metrics):
        cols[i % 4].metric(label, value)

    tabs = st.tabs(["AI Explanation", "Overview", "Repository Structure", "Files & Folders", "Technical Details"])

    with tabs[0]:
        st.markdown(data["explanation"])

    with tabs[1]:
        st.subheader("Repository Overview")
        st.write(f"**Repository:** {report['owner']}/{report['repository']}")
        st.write(f"**Default branch:** {report.get('default_branch') or 'unknown'}")
        st.write(f"**URL:** {report['url']}")
        st.subheader("Languages")
        st.json(report["languages"])
        st.subheader("Detected Technologies")
        if report["technologies"]:
            st.write(" · ".join(report["technologies"]))
        else:
            st.info("No technology could be confidently detected from the supplied evidence.")

    with tabs[2]:
        st.subheader("Folder Tree")
        st.code("\n".join(report["folder_tree"][:400]) or "No folder tree available.")

    with tabs[3]:
        st.subheader("Analyzed File Inventory")
        for item in report["files"]:
            with st.container(border=True):
                st.markdown(f"**{item['path']}**")
                st.caption(f"{item['category']} · {item.get('language') or 'unknown'} · {human_size(item['size'])}")
                if item.get("summary"):
                    st.write(item["summary"])

    with tabs[4]:
        st.subheader("LLM Context Optimization")
        st.write(f"Selected files for local model: **{len(report['context_files'])}**")
        st.write(f"LLM context size: **{report['context_characters']:,} characters**")
        st.write("The full repository is inventoried, but only the most relevant readable evidence is sent to the local model to reduce latency.")
        st.code("\n".join(report["context_files"]) or "No readable context files selected.")
        st.subheader("Performance")
        st.json(data.get("timings", {}))


def main(local_backend_ready: bool | None = None) -> None:
    inject_css()
    st.markdown(
        '<div class="hero"><h1>🧠 REPOSITORY CODE EXPLAINER</h1><p>Understand any public GitHub repository in simple language using a locally running open-source model.</p>'
        '<span class="badge">FastAPI</span><span class="badge">Streamlit</span><span class="badge">GitPython</span><span class="badge">Hugging Face Transformers</span><span class="badge">SmolLM2 135M</span></div>',
        unsafe_allow_html=True,
    )

    with st.sidebar:
        st.header("Local GenAI Pipeline")
        st.write("GitHub → GitPython → Repository Analyzer → Smart Context → Local Transformers Model → Explanation")
        st.caption(f"Backend: {BACKEND_URL}")
        try:
            health = get_json(f"{BACKEND_URL}/api/health", timeout=5)
            if health.get("local_llm_available"):
                if health.get("model_loaded"):
                    st.success(f"Local model loaded · {health.get('model', 'local model')}")
                else:
                    st.info(f"Local model ready; it will download/load on first analysis · {health.get('model', 'local model')}")
            else:
                st.error("The local Hugging Face inference dependencies are unavailable. Check requirements.txt and redeploy.")
        except Exception:
            if local_backend_ready is False and BACKEND_URL.startswith(("http://127.0.0.1", "http://localhost")):
                st.error("FastAPI backend could not be started. Run: uvicorn backend.main:app --host 127.0.0.1 --port 8000")
            else:
                st.error("The embedded FastAPI backend could not be started. Refresh the app and try again.")
        st.divider()
        st.write("Only public HTTPS GitHub repositories are accepted. Repository code is never executed, and sensitive file contents are withheld from the local model.")

    st.subheader("Explain this GitHub Repository")
    repository_url = st.text_input(
        "GitHub repository URL",
        placeholder="https://github.com/username/repository",
        help="Any public GitHub repository can be analyzed.",
    )
    analyze = st.button("🚀 Analyze Repository", type="primary", use_container_width=True)

    if analyze:
        if not repository_url.strip():
            st.error("Please enter a GitHub repository URL.")
            return
        try:
            queued = start_job(repository_url)
            result = poll_job(queued["job_id"])
            render_report(result)
        except requests.Timeout:
            st.error("The backend request timed out before a job could be started. Check that FastAPI is reachable.")
        except requests.RequestException as exc:
            st.error(f"Cannot reach the FastAPI backend: {exc}")
        except TimeoutError as exc:
            st.warning(str(exc))
        except Exception as exc:
            st.error(str(exc))


if __name__ == "__main__":
    main()
